### ISSUE TITLE
Something went wrong when trying to create page from wknd project archetype

### ISSUE THREAD

**Issue by msdauris** [adobe/aem-guides-wknd#434]
### Expected Behaviour

Able to create content page from wknd project archetype

### Actual Behaviour
Something went wrong when creating content page from wknd project

#### Steps to Reproduce

issue appears after fresh install and clean crx-quickstart folder

aem set up and running on local machine. http://localhost:4502/sites.html/content

`mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
    -D archetypeGroupId=com.adobe.aem \
    -D archetypeArtifactId=aem-project-archetype \
    -D archetypeVersion=47 \
    -D appTitle="WKND Sites Project" \
    -D appId="wknd" \
    -D groupId="com.adobe.aem.guides" \
    -D artifactId="aem-guides-wknd" \
    -D package="com.adobe.aem.guides.wknd" \
    -D version="0.0.1-SNAPSHOT" \
    -D aemVersion="6.5.0"`

also tried 

`mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
    -D archetypeGroupId=com.adobe.aem \
    -D archetypeArtifactId=aem-project-archetype \
    -D archetypeVersion=41 \
    -D appTitle="WKND Sites Project" \
    -D appId="wknd" \
    -D groupId="com.adobe.aem.guides" \
    -D artifactId="aem-guides-wknd" \
    -D package="com.adobe.aem.guides.wknd" \
    -D version="0.0.1-SNAPSHOT" \
    -D aemVersion="6.5.0"`

mvn clean install -PautoInstallSinglePackage -Pclassic

#### Platform and Version

aem 6.5.0

java --version
java 11.0.20 2023-07-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.20+9-LTS-256)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.20+9-LTS-256, mixed mode)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /opt/homebrew/Cellar/maven/3.9.6/libexec
Java version: 11.0.20, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "13.3", arch: "aarch64", family: "mac"

#### Logs taken while reproducing problem

`12.12.2023 17:28:54.302 *ERROR* [sling-default-4-health-com.day.cq.compat.codeupgrade.impl.hc.MissingPackagesHealthCheck] com.adobe.granite.queries.impl.hc.QueryHealthCheckMetrics Error in refreshing the health check gauge
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1480105 path $.data[580].contentPackage
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) [com.adobe.cq.gson:2.8.5]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) [com.adobe.cq.gson:2.8.5]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) [com.adobe.cq.gson:2.8.5]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) [com.adobe.cq.gson:2.8.5]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) [com.adobe.cq.gson:2.8.5]
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:865)
	at com.day.cq.compat.codeupgrade.impl.hc.MissingPackagesHealthCheck.getMissingBundleAndContentPackage(MissingPackagesHealthCheck.java:255) [com.day.cq.cq-compat-codeupgrade:1.7.100]
	at com.day.cq.compat.codeupgrade.impl.hc.MissingPackagesHealthCheck.addMissingPackagesLogsToSet(MissingPackagesHealthCheck.java:226) [com.day.cq.cq-compat-codeupgrade:1.7.100]
	at com.day.cq.compat.codeupgrade.impl.hc.MissingPackagesHealthCheck.execute(MissingPackagesHealthCheck.java:147) [com.day.cq.cq-compat-codeupgrade:1.7.100]
	at com.adobe.granite.queries.impl.hc.QueryHealthCheckMetrics$LazyGauge.execute(QueryHealthCheckMetrics.java:266) [com.adobe.granite.queries:1.0.64]
	at com.adobe.granite.queries.impl.hc.QueryHealthCheckMetrics$LazyGauge.lambda$new$0(QueryHealthCheckMetrics.java:253) [com.adobe.granite.queries:1.0.64]
	at org.apache.sling.commons.scheduler.impl.QuartzJobExecutor.execute(QuartzJobExecutor.java:347) [org.apache.sling.commons.scheduler:2.7.2]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org.apache.sling.commons.scheduler:2.7.2]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1480105 path $.data[580].contentPackage
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825) [com.adobe.cq.gson:2.8.5]
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402) [com.adobe.cq.gson:2.8.5]
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390) [com.adobe.cq.gson:2.8.5]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) [com.adobe.cq.gson:2.8.5]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) [com.adobe.cq.gson:2.8.5]
	... 16 common frames omitted`

additional logs

12.12.2023 15:09:14.195 *ERROR* [0:0:0:0:0:0:0:1 [1702390153809] GET /mnt/overlay/wcm/core/content/sites/createpagewizard/properties.html/conf/wknd/settings/wcm/templates/page-content HTTP/1.1] libs.granite.ui.components.foundation.form.field Unable to render field
org.apache.sling.api.scripting.ScriptEvaluationException: javax.servlet.ServletException: javax.servlet.jsp.JspException: Error while executing script render.html

**Comment by msdauris** [comment]
![create page server 500](https://github.com/adobe/aem-guides-wknd/assets/105852666/9cb81993-b871-47d8-826f-3b806a84b9fa)

**Comment by msdauris** [comment]
issue resolved with sp17
