### ISSUE TITLE
4 errors when building from master straight after checkout

### ISSUE THREAD

**Issue by Duduc94** [adobe/aem-guides-wknd#460]
### Expected Behaviour
Expecting mvn clean install -PautoInstallSinglePackage to successfully build and instal package to AEM.

### Actual Behaviour
Getting 4 errors:

Uploaded the full output, but in short, the errors are the following:

[INFO] Reactor Summary:
[INFO]
[INFO] WKND Sites Project - Reactor Project ............... SUCCESS [  0.296 s]
[INFO] WKND Sites Project - Core .......................... FAILURE [  4.726 s]
[INFO] WKND Sites Project - UI Frontend ................... SKIPPED
[INFO] WKND Sites Project - UI apps structure ............. SKIPPED
[INFO] WKND Sites Project - UI apps ....................... SKIPPED
[INFO] WKND Sites Project - UI content .................... SKIPPED
[INFO] WKND Sites Project - UI config ..................... SKIPPED
[INFO] WKND Sites Project - UI sample content ............. SKIPPED
[INFO] WKND Sites Project - All ........................... SKIPPED
[INFO] WKND Sites Project - Integration Tests ............. SKIPPED
[INFO] WKND Sites Project - Dispatcher .................... SKIPPED
[INFO] WKND Sites Project - UI Tests ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.876 s
[INFO] Finished at: 2024-06-21T11:08:41+03:00
[INFO] Final Memory: 56M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2:baseline (baseline) on project aem-guides-wknd.core: Execution baseline of goal biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2:baseline failed: Unable to load the mojo 'baseline' (or one of its required components) from the plugin 'biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2': com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger
[ERROR] while locating org.apache.maven.repository.internal.DefaultVersionRangeResolver
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.VersionRangeResolver
[ERROR] for parameter 2 at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.DependencyCollector
[ERROR] for parameter 5 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
[ERROR] while locating java.lang.Object annotated with *
[ERROR] while locating aQute.bnd.maven.baseline.plugin.BaselineMojo
[ERROR] at ClassRealm[plugin>biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2:baseline)
[ERROR] Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory

2) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionResolver.logger
[ERROR] while locating org.apache.maven.repository.internal.DefaultVersionResolver
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.VersionResolver
[ERROR] for parameter 2 at org.eclipse.aether.internal.impl.DefaultArtifactResolver.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.DefaultArtifactResolver
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.ArtifactResolver
[ERROR] for parameter 2 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
[ERROR] while locating java.lang.Object annotated with *
[ERROR] while locating aQute.bnd.maven.baseline.plugin.BaselineMojo
[ERROR] at ClassRealm[plugin>biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2:baseline)
[ERROR] Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory

3) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionResolver.logger
[ERROR] while locating org.apache.maven.repository.internal.DefaultVersionResolver
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.VersionResolver
[ERROR] for parameter 1 at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.<init>(Unknown Source)
[ERROR] while locating org.apache.maven.repository.internal.DefaultArtifactDescriptorReader
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.ArtifactDescriptorReader
[ERROR] for parameter 1 at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.DependencyCollector
[ERROR] for parameter 5 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
[ERROR] while locating java.lang.Object annotated with *
[ERROR] while locating aQute.bnd.maven.baseline.plugin.BaselineMojo
[ERROR] at ClassRealm[plugin>biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2:baseline)
[ERROR] Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory

4) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionResolver.logger
[ERROR] while locating org.apache.maven.repository.internal.DefaultVersionResolver
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.VersionResolver
[ERROR] for parameter 2 at org.eclipse.aether.internal.impl.DefaultArtifactResolver.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.DefaultArtifactResolver
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.ArtifactResolver
[ERROR] for parameter 2 at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.<init>(Unknown Source)
[ERROR] while locating org.apache.maven.repository.internal.DefaultArtifactDescriptorReader
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.ArtifactDescriptorReader
[ERROR] for parameter 1 at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.DependencyCollector
[ERROR] for parameter 5 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
[ERROR] while locating java.lang.Object annotated with *
[ERROR] while locating aQute.bnd.maven.baseline.plugin.BaselineMojo
[ERROR] at ClassRealm[plugin>biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=biz.aQute.bnd:bnd-baseline-maven-plugin:5.1.2:baseline)
[ERROR] Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory

[command log.pdf](https://github.com/user-attachments/files/15924832/command.log.pdf)

#### Steps to Reproduce
Running mvn clean install -PautoInstallSinglePackage on master branch after cloning the repository 

#### Platform and Version
Using maven: 3.3.9
openjdk 11.0.14.1 2022-02-08
OpenJDK Runtime Environment JBR-11.0.14.1.1-2043.11-jcef (build 11.0.14.1+1-b2043.11)
OpenJDK 64-Bit Server VM JBR-11.0.14.1.1-2043.11-jcef (build 11.0.14.1+1-b2043.11, mixed mode)

**Comment by SachinMali** [comment]
That's strange, not sure if it is a Java version or Maven, I tried just now, worked as expected, see below. Maybe someone from this community can cross-verify and let us know if reproducible. 


[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WKND Sites Project - Reactor Project 3.2.1-SNAPSHOT:
[INFO] 
[INFO] WKND Sites Project - Reactor Project ............... SUCCESS [  0.299 s]
[INFO] WKND Sites Project - Core .......................... SUCCESS [  9.824 s]
[INFO] WKND Sites Project - UI Frontend ................... SUCCESS [ 23.919 s]
[INFO] WKND Sites Project - UI apps structure ............. SUCCESS [  0.465 s]
[INFO] WKND Sites Project - UI apps ....................... SUCCESS [  0.730 s]
[INFO] WKND Sites Project - UI content .................... SUCCESS [  0.180 s]
[INFO] WKND Sites Project - UI config ..................... SUCCESS [  0.056 s]
[INFO] WKND Sites Project - UI sample content ............. SUCCESS [  0.457 s]
[INFO] WKND Sites Project - All ........................... SUCCESS [ 30.076 s]
[INFO] WKND Sites Project - Integration Tests ............. SUCCESS [  5.153 s]
[INFO] WKND Sites Project - Dispatcher .................... SUCCESS [  0.116 s]
[INFO] WKND Sites Project - UI Tests ...................... SUCCESS [  0.268 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:12 min
[INFO] Finished at: 2024-06-21T11:49:28-04:00
[INFO] ------------------------------------------------------------------------
$mvn -v
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /Users/sm/.sdkman/candidates/maven/current
Java version: 11.0.16, vendor: Amazon.com Inc., runtime: /Users/sm/.sdkman/candidates/java/11.0.16-amzn
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "14.5", arch: "aarch64", family: "mac"
$java -version
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Corretto-11.0.16.8.1 (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.16.8.1 (build 11.0.16+8-LTS, mixed mode)
